// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyqDU3DojdwWPTQI6m4XS8O4vNngTWBA',
    appId: '1:54979972844:web:84de0f3d8e2880cf1a1fc9',
    messagingSenderId: '54979972844',
    projectId: 'conference-c2e4b',
    authDomain: 'conference-c2e4b.firebaseapp.com',
    storageBucket: 'conference-c2e4b.appspot.com',
    measurementId: 'G-ZGKSFZFH5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpq0SxO9w0lqpXrYm64jx7Bxt77oMb6pc',
    appId: '1:54979972844:android:f14767a74d35b3c41a1fc9',
    messagingSenderId: '54979972844',
    projectId: 'conference-c2e4b',
    storageBucket: 'conference-c2e4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNvkhdsKGPeoJB4uHkITn89KSCqmB60m8',
    appId: '1:54979972844:ios:e764052f498203d01a1fc9',
    messagingSenderId: '54979972844',
    projectId: 'conference-c2e4b',
    storageBucket: 'conference-c2e4b.appspot.com',
    iosBundleId: 'com.example.myp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNvkhdsKGPeoJB4uHkITn89KSCqmB60m8',
    appId: '1:54979972844:ios:8d15262c44602ff71a1fc9',
    messagingSenderId: '54979972844',
    projectId: 'conference-c2e4b',
    storageBucket: 'conference-c2e4b.appspot.com',
    iosBundleId: 'com.example.myp.RunnerTests',
  );
}
